//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUCapture_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AUCapture_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoMuteUs.
        /// </summary>
        public static string ConnectionStatus_AUTOMUTEUS {
            get {
                return ResourceManager.GetString("ConnectionStatus.AUTOMUTEUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Bot.
        /// </summary>
        public static string ConnectionStatus_USER_BOT {
            get {
                return ResourceManager.GetString("ConnectionStatus.USER BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game code.
        /// </summary>
        public static string GameCodeTooltip {
            get {
                return ResourceManager.GetString("GameCodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game code.
        /// </summary>
        public static string GameCodeWatermark {
            get {
                return ResourceManager.GetString("GameCodeWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCUSSION.
        /// </summary>
        public static string GameState_DISCUSSION {
            get {
                return ResourceManager.GetString("GameState.DISCUSSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDED.
        /// </summary>
        public static string GameState_ENDED {
            get {
                return ResourceManager.GetString("GameState.ENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOBBY.
        /// </summary>
        public static string GameState_LOBBY {
            get {
                return ResourceManager.GetString("GameState.LOBBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        public static string GameState_MENU {
            get {
                return ResourceManager.GetString("GameState.MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASKS.
        /// </summary>
        public static string GameState_TASKS {
            get {
                return ResourceManager.GetString("GameState.TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        public static string GameState_UNKNOWN {
            get {
                return ResourceManager.GetString("GameState.UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current status.
        /// </summary>
        public static string GameStateTooltip {
            get {
                return ResourceManager.GetString("GameStateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code: .
        /// </summary>
        public static string ManualConnectionCode {
            get {
                return ResourceManager.GetString("ManualConnectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Connection.
        /// </summary>
        public static string ManualConnectionHeader {
            get {
                return ResourceManager.GetString("ManualConnectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host: .
        /// </summary>
        public static string ManualConnectionHost {
            get {
                return ResourceManager.GetString("ManualConnectionHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ManualConnectionSubmitButton {
            get {
                return ResourceManager.GetString("ManualConnectionSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the manual connection window.
        /// </summary>
        public static string ManualConnectTooltip {
            get {
                return ResourceManager.GetString("ManualConnectTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current map.
        /// </summary>
        public static string MapTooltip {
            get {
                return ResourceManager.GetString("MapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string MapWatermark {
            get {
                return ResourceManager.GetString("MapWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OffText {
            get {
                return ResourceManager.GetString("OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OnText {
            get {
                return ResourceManager.GetString("OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get AutoMuteUs premium.
        /// </summary>
        public static string PremiumTooltip {
            get {
                return ResourceManager.GetString("PremiumTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We detected an update to {0}, But there is no public key in this capture so we will not be able to verify integrity. Please download the latest release off the github page..
        /// </summary>
        public static string PrivateKeyErrorMessage {
            get {
                return ResourceManager.GetString("PrivateKeyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoUpdater failed.
        /// </summary>
        public static string PrivateKeyErrorTitle {
            get {
                return ResourceManager.GetString("PrivateKeyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry.
        /// </summary>
        public static string RetryText {
            get {
                return ResourceManager.GetString("RetryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version:.
        /// </summary>
        public static string SettingsAboutTabAppVersion {
            get {
                return ResourceManager.GetString("SettingsAboutTabAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto updater.
        /// </summary>
        public static string SettingsAboutTabAutoUpdaterHeader {
            get {
                return ResourceManager.GetString("SettingsAboutTabAutoUpdaterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors: .
        /// </summary>
        public static string SettingsAboutTabContributorsButton {
            get {
                return ResourceManager.GetString("SettingsAboutTabContributorsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show contributors.
        /// </summary>
        public static string SettingsAboutTabContributorsButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsAboutTabContributorsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SettingsAboutTabHeader {
            get {
                return ResourceManager.GetString("SettingsAboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version:.
        /// </summary>
        public static string SettingsAboutTabLatestVersion {
            get {
                return ResourceManager.GetString("SettingsAboutTabLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log folder.
        /// </summary>
        public static string SettingsDebugOpenLogsFolderButton {
            get {
                return ResourceManager.GetString("SettingsDebugOpenLogsFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode.
        /// </summary>
        public static string SettingsDebugTabDebugModeSwitch {
            get {
                return ResourceManager.GetString("SettingsDebugTabDebugModeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string SettingsDebugTabHeader {
            get {
                return ResourceManager.GetString("SettingsDebugTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload offsets.
        /// </summary>
        public static string SettingsDebugTabReloadOffsetsButton {
            get {
                return ResourceManager.GetString("SettingsDebugTabReloadOffsetsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Config.
        /// </summary>
        public static string SettingsDebugTabResetConfigButton {
            get {
                return ResourceManager.GetString("SettingsDebugTabResetConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string SettingsDiscordTabHeader {
            get {
                return ResourceManager.GetString("SettingsDiscordTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SettingsDiscordTabSubmitButton {
            get {
                return ResourceManager.GetString("SettingsDiscordTabSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste token here.
        /// </summary>
        public static string SettingsDiscordTabTokenWatermark {
            get {
                return ResourceManager.GetString("SettingsDiscordTabTokenWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always copy game code.
        /// </summary>
        public static string SettingsGeneralTabAlwaysCopyGameCode {
            get {
                return ResourceManager.GetString("SettingsGeneralTabAlwaysCopyGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No end judgment by exile.
        /// </summary>
        public static string SettingsGeneralTabNoEndJudgmentByExile {
            get {
                return ResourceManager.GetString("SettingsGeneralTabNoEndJudgmentByExile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string SettingsGeneralTabAlwaysOnTop {
            get {
                return ResourceManager.GetString("SettingsGeneralTabAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Server.
        /// </summary>
        public static string SettingsGeneralTabAPIServer {
            get {
                return ResourceManager.GetString("SettingsGeneralTabAPIServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus window on connect.
        /// </summary>
        public static string SettingsGeneralTabFocusOnConnect {
            get {
                return ResourceManager.GetString("SettingsGeneralTabFocusOnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsGeneralTabHeader {
            get {
                return ResourceManager.GetString("SettingsGeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsGeneralTabLanguageHeader {
            get {
                return ResourceManager.GetString("SettingsGeneralTabLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SettingsGeneralTabStartupMemes {
            get {
                return ResourceManager.GetString("SettingsGeneralTabStartupMemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the settings window.
        /// </summary>
        public static string SettingsTooltip {
            get {
                return ResourceManager.GetString("SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUCapture.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No thanks.
        /// </summary>
        public static string UpdateNotificationDecline {
            get {
                return ResourceManager.GetString("UpdateNotificationDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution.
        /// </summary>
        public static string UpdateNotificationHeader {
            get {
                return ResourceManager.GetString("UpdateNotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve detected you&apos;re using an older version of AmongUsCapture!
        ///Your version: {0}
        ///Latest version: {1}.
        /// </summary>
        public static string UpdateNotificationMessage {
            get {
                return ResourceManager.GetString("UpdateNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateNotificationUpdate {
            get {
                return ResourceManager.GetString("UpdateNotificationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Among Us.
        /// </summary>
        public static string WaitingForAmongUs {
            get {
                return ResourceManager.GetString("WaitingForAmongUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Lobby.
        /// </summary>
        public static string WaitingForLobby {
            get {
                return ResourceManager.GetString("WaitingForLobby", resourceCulture);
            }
        }
    }
}
