builds:
- skip: true

release:
    extra_files:
        - glob: ./AUCapture-WPF/bin/Release/netcoreapp3.1/publish/AmongUsCapture.exe
        - glob: ./amonguscapture/AUCapture-WPF/bin/Release/netcoreapp3.1/publish/AmongUsCapture.exe